AllCops:
  TargetRubyVersion: 2.6.3

Bundler/OrderedGems:
  Enabled: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Lint/ImplicitStringConcatenation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Security/Open:
  Enabled: true

Style/UnneededPercentQ:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SingleLineBlockParams:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/SelfAssignment:
  Enabled: false

Style/RedundantReturn:
  Enabled: true

Naming/UncommunicativeMethodParamName:
  Enabled: true

Metrics/AbcSize:
  Max: 30

Metrics/BlockNesting:
  Max: 4

Metrics/BlockLength:
  Max: 50s

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Metrics/LineLength:
  Enabled: true

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Enabled: true

Naming/MethodName:
  Enabled: true

Rails:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true
